### ISSUE TITLE
Snippets aren't showing up

### ISSUE THREAD

**Issue by erihanse** [GoogleCloudPlatform/cloud-code-vscode#134]
Issue Type: <b>Bug</b>

I'm trying to get the Skaffold snippets to work. When I run the command "Insert snippet" nothing is shown. 

Extension version: 0.0.11
VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:25.463Z)
OS version: Linux x64 5.0.0-25-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|31.12GB (1.14GB free)|
|Process Argv|--unity-launch /home/erikah/Downloads/helm-exporter_rev2.json|
|Screen Reader|no|
|VM|0%|
</details>

Console log:
```
[Extension Host] debugger listening on port 27073
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4084 Overwriting grammar scope name to file mapping for scope source.python.
Old grammar file: file:///usr/share/code/resources/app/extensions/python/syntaxes/MagicPython.tmLanguage.json.
New grammar file: file:///home/erikah/.vscode/extensions/magicstack.magicpython-1.1.0/grammars/MagicPython.tmLanguage
register @ /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4084
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4084 Overwriting grammar scope name to file mapping for scope source.sql.
Old grammar file: file:///usr/share/code/resources/app/extensions/sql/syntaxes/sql.tmLanguage.json.
New grammar file: file:///home/erikah/.vscode/extensions/ms-mssql.mssql-1.6.0/syntaxes/SQL.plist
register @ /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4084
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4084 Overwriting grammar scope name to file mapping for scope source.ruby.
Old grammar file: file:///usr/share/code/resources/app/extensions/ruby/syntaxes/ruby.tmLanguage.json.
New grammar file: file:///home/erikah/.vscode/extensions/rebornix.ruby-0.24.2/syntaxes/ruby.cson.json
register @ /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4084
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4084 Overwriting grammar scope name to file mapping for scope source.yaml.
Old grammar file: file:///usr/share/code/resources/app/extensions/yaml/syntaxes/yaml.tmLanguage.json.
New grammar file: file:///home/erikah/.vscode/extensions/redhat.vscode-yaml-0.5.1/syntaxes/yaml.tmLanguage.json
register @ /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4084
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4084 Overwriting grammar scope name to file mapping for scope source.scala.
Old grammar file: file:///home/erikah/.vscode/extensions/lightbend.vscode-sbt-scala-0.2.4/syntaxes/Scala.tmLanguage.
New grammar file: file:///home/erikah/.vscode/extensions/scala-lang.scala-0.3.4/syntaxes/Scala.tmLanguage.json
register @ /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4084
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4084 Overwriting grammar scope name to file mapping for scope source.groovy.
Old grammar file: file:///usr/share/code/resources/app/extensions/groovy/syntaxes/groovy.tmLanguage.json.
New grammar file: file:///home/erikah/.vscode/extensions/secanis.jenkinsfile-support-0.1.0/syntaxes/groovy.tmLanguage
register @ /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4084
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:242 [Extension Host] [before-after-hook]: "Hook()" repurposing warning, use "Hook.Collection()". Read more: https://git.io/upgrade-before-after-hook-to-1.4
t.log @ /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:242
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:242 [Extension Host] Congratulations, your extension "vscode-ansible" is now active!
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2477 Google Cloud SDK not found. Do you want to install it?
onDidNotificationChange @ /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2477
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:242 [Extension Host] (node:13033) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
t.log @ /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:242
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2477 Request initialize failed with message: ENOENT: no such file or directory, open '/home/erikah/ok/plattform/helm-exporter/vendor/k8s.io/helm/pkg/downloader/testdata/helmhome/repository/cache/local-index.yaml'
onDidNotificationChange @ /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2477
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:3348 Activating extension 'googlecloudtools.cloudcode' failed: Request initialize failed with message: ENOENT: no such file or directory, open '/home/erikah/ok/plattform/helm-exporter/vendor/k8s.io/helm/pkg/downloader/testdata/helmhome/repository/cache/local-index.yaml'.
_logMessageInConsole @ /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:3348
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:242 [Extension Host] Activating extension `googlecloudtools.cloudcode` failed:  Request initialize failed with message: ENOENT: no such file or directory, open '/home/erikah/ok/plattform/helm-exporter/vendor/k8s.io/helm/pkg/downloader/testdata/helmhome/repository/cache/local-index.yaml'
t.log @ /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:242
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:242 [Extension Host] Here is the error stack:  Error: Request initialize failed with message: ENOENT: no such file or directory, open '/home/erikah/ok/plattform/helm-exporter/vendor/k8s.io/helm/pkg/downloader/testdata/helmhome/repository/cache/local-index.yaml'
	at /home/erikah/.vscode/extensions/googlecloudtools.cloudcode-0.0.11/dist/extension.js:9:98900
	at /home/erikah/.vscode/extensions/googlecloudtools.cloudcode-0.0.11/dist/extension.js:9:99194
	at Immediate.I.V.N.size.setImmediate (/home/erikah/.vscode/extensions/googlecloudtools.cloudcode-0.0.11/dist/extension.js:9:99555)
	at runCallback (timers.js:694:18)
	at tryOnImmediate (timers.js:665:5)
	at processImmediate (timers.js:647:5)
	at process.topLevelDomainCallback (domain.js:121:23)
```

**Comment by erihanse** [comment]
> [Extension Host] debugger listening on port 27073
> /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4084 Overwriting grammar scope name to file mapping for scope source.python.
> Old grammar file: file:///usr/share/code/resources/app/extensions/python/syntaxes/MagicPython.tmLanguage.json.
> New grammar file: file:///home/erikah/.vscode/extensions/magicstack.magicpython-1.1.0/grammars/MagicPython.tmLanguage
> register @ /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4084
> /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4084 Overwriting grammar scope name to file mapping for scope source.sql.
> Old grammar file: file:///usr/share/code/resources/app/extensions/sql/syntaxes/sql.tmLanguage.json.
> New grammar file: file:///home/erikah/.vscode/extensions/ms-mssql.mssql-1.6.0/syntaxes/SQL.plist
> register @ /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4084
> /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4084 Overwriting grammar scope name to file mapping for scope source.ruby.
> Old grammar file: file:///usr/share/code/resources/app/extensions/ruby/syntaxes/ruby.tmLanguage.json.
> New grammar file: file:///home/erikah/.vscode/extensions/rebornix.ruby-0.24.2/syntaxes/ruby.cson.json
> register @ /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4084
> /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4084 Overwriting grammar scope name to file mapping for scope source.yaml.
> Old grammar file: file:///usr/share/code/resources/app/extensions/yaml/syntaxes/yaml.tmLanguage.json.
> New grammar file: file:///home/erikah/.vscode/extensions/redhat.vscode-yaml-0.5.1/syntaxes/yaml.tmLanguage.json
> register @ /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4084
> /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4084 Overwriting grammar scope name to file mapping for scope source.scala.
> Old grammar file: file:///home/erikah/.vscode/extensions/lightbend.vscode-sbt-scala-0.2.4/syntaxes/Scala.tmLanguage.
> New grammar file: file:///home/erikah/.vscode/extensions/scala-lang.scala-0.3.4/syntaxes/Scala.tmLanguage.json
> register @ /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4084
> /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4084 Overwriting grammar scope name to file mapping for scope source.groovy.
> Old grammar file: file:///usr/share/code/resources/app/extensions/groovy/syntaxes/groovy.tmLanguage.json.
> New grammar file: file:///home/erikah/.vscode/extensions/secanis.jenkinsfile-support-0.1.0/syntaxes/groovy.tmLanguage
> register @ /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4084
> /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:242 [Extension Host] [before-after-hook]: "Hook()" repurposing warning, use "Hook.Collection()". Read more: https://git.io/upgrade-before-after-hook-to-1.4
> t.log @ /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:242
> /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:242 [Extension Host] Congratulations, your extension "vscode-ansible" is now active!
> /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2477 Google Cloud SDK not found. Do you want to install it?
> onDidNotificationChange @ /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2477
> /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:242 [Extension Host] (node:13033) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
> t.log @ /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:242
> /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2477 Request initialize failed with message: ENOENT: no such file or directory, open '/home/erikah/ok/plattform/helm-exporter/vendor/k8s.io/helm/pkg/downloader/testdata/helmhome/repository/cache/local-index.yaml'
> onDidNotificationChange @ /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:2477
> /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:3348 Activating extension 'googlecloudtools.cloudcode' failed: Request initialize failed with message: ENOENT: no such file or directory, open '/home/erikah/ok/plattform/helm-exporter/vendor/k8s.io/helm/pkg/downloader/testdata/helmhome/repository/cache/local-index.yaml'.
> _logMessageInConsole @ /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:3348
> /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:242 [Extension Host] Activating extension `googlecloudtools.cloudcode` failed:  Request initialize failed with message: ENOENT: no such file or directory, open '/home/erikah/ok/plattform/helm-exporter/vendor/k8s.io/helm/pkg/downloader/testdata/helmhome/repository/cache/local-index.yaml'
> t.log @ /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:242
> /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:242 [Extension Host] Here is the error stack:  Error: Request initialize failed with message: ENOENT: no such file or directory, open '/home/erikah/ok/plattform/helm-exporter/vendor/k8s.io/helm/pkg/downloader/testdata/helmhome/repository/cache/local-index.yaml'
> 	at /home/erikah/.vscode/extensions/googlecloudtools.cloudcode-0.0.11/dist/extension.js:9:98900
> 	at /home/erikah/.vscode/extensions/googlecloudtools.cloudcode-0.0.11/dist/extension.js:9:99194
> 	at Immediate.I.V.N.size.setImmediate (/home/erikah/.vscode/extensions/googlecloudtools.cloudcode-0.0.11/dist/extension.js:9:99555)
> 	at runCallback (timers.js:694:18)
> 	at tryOnImmediate (timers.js:665:5)
> 	at processImmediate (timers.js:647:5)
> 	at process.topLevelDomainCallback (domain.js:121:23)

**Comment by erihanse** [comment]
Thanks for getting back to me. I re-added the vendor folder, and suddenly it started working again. I do believe the file was missing, just didn't expect the snippets to stop working for that reason. I have a single workspace opened. I believe we can close this.
