### ISSUE TITLE
Managed dependencies are currently unavailable. 

### ISSUE THREAD

**Issue by stevereaver** [GoogleCloudPlatform/cloud-code-vscode#477]
Cloud Code Extension version:
1.14.1

VSCode version:
1.60.2

OS: 
Ubuntu 20.04

Cloud SDK:
Google Cloud SDK 358.0.0
alpha 2021.09.17
beta 2021.09.17
bq 2.0.71
config-connector 1.61.0
core 2021.09.17
gsutil 4.68
kpt 1.0.0-beta.4

Skaffold: 
n/a

Kubectl:
n/a

**Description**:
Installing this plugin breaks gcloud command from within VSCODE Terminal and causes following error, when installed

```
Managed dependencies are currently unavailable.  Failed to install managed dependencies successfully too many times, will reattempt after Visual Studio Code is restarted. Failed to update Cloud SDK to the latest version. Traceback (most recent call last):
  File "/home/reaver/.cache/cloud-code/installer/google-cloud-sdk/lib/gcloud.py", line 104, in <module>
    main()
  File "/home/reaver/.cache/cloud-code/installer/google-cloud-sdk/lib/gcloud.py", line 62, in main
    from googlecloudsdk.core.util import encoding
  File "/home/reaver/.cache/cloud-code/installer/google-cloud-sdk/lib/googlecloudsdk/__init__.py", line 23, in <module>
    from googlecloudsdk.core.util import importing
ModuleNotFoundError: No module named 'googlecloudsdk.core'
```

Then when running a gcloud command this is what happens
```
reaver@sulaco:~/Seafile/Kasna/devops/cloud-builders/musketeers$ gcloud config list
Traceback (most recent call last):
  File "/home/reaver/.cache/cloud-code/installer/google-cloud-sdk/lib/gcloud.py", line 104, in <module>
    main()
  File "/home/reaver/.cache/cloud-code/installer/google-cloud-sdk/lib/gcloud.py", line 62, in main
    from googlecloudsdk.core.util import encoding
  File "/home/reaver/.cache/cloud-code/installer/google-cloud-sdk/lib/googlecloudsdk/__init__.py", line 23, in <module>
    from googlecloudsdk.core.util import importing
ModuleNotFoundError: No module named 'googlecloudsdk.core'
```

**Repro step**:
Install plugin, run any gcloud command from terminal within VSCODE.
Remove plugin, problem goes away.

**Comment by kschaab** [comment]
@stevereaver would you mind trying `rm -rf /home/reaver/.cache/cloud-code/installer` to see if this helps at all?  It seems like we are detecting this is not usable and reinstalling the managed `gcloud` instance but for some reason it keeps failing.  If you turn on Cloud Code verbose logging, reload VS Code (ctrl-shift-p - "Developer: Reload Window"), and send us the relevant parts of the output that would be helpful:
![image](https://user-images.githubusercontent.com/7329029/135526616-02edc110-0181-4eeb-8630-164c7cca1a4e.png)

Another thing you can do is just turn off managed dependencies, but this will require you to install kubectl, minikube, and skaffold manually.

**Comment by stevereaver** [comment]
ok yes, rm on that dir that has fixed it. Thanks.
