### ISSUE TITLE
Cannot start the Apigee emulator version 1.10.3

### ISSUE THREAD

**Issue by pyonk** [GoogleCloudPlatform/cloud-code-vscode#851]
**Environment**:
*(Hint: "Report Extension Issue on Github" command will fill these out for you.)*

**Version information**

Cloud Code Extension version: v2.0.0

VSCode version:

```
Version: 1.82.2 (Universal)
Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
Date: 2023-09-14T05:59:47.790Z (1 wk ago)
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.6.0
```
Cloud SDK: 408.0.1

Rancher Desktop: 1.9.1

**Description**:
The Apigee emulator version `1.10.3` doesn't start with Rancher Desktop.

**Repro step**:
Pull the Apigee emulator version `1.10.3`, and create a container through the CloudCode extension on VScode.
And run this command on your terminal to see the logs.
```
$ docker logs -f {{your container name}}
```

Then, you will see the following log and exit.

```
Cassandra has started successfully
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/apigee/config/ConfigUtil has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)
apigee-configutil: apigee-emulator: # Failed
/opt/apigee/emulator-entry.sh: line 42: /opt/apigee/apigee-emulator/lib/settings: No such file or directory
/opt/apigee/emulator-entry.sh: line 48: -Djava.io.tmpdir=/opt/apigee/data: No such file or directory
```

**Comment by shirishtrivikr** [comment]
@pyonk Thank you for reporting the issue, We are looking into it.

**Comment by shirishtrivikr** [comment]
@pyonk We have fixed the emulator image in the GCR.  Please remove the existing docker image before you try the latest one.
