### ISSUE TITLE
Duet AI doesn't work on arm64

### ISSUE THREAD

**Issue by kalona** [GoogleCloudPlatform/cloud-code-vscode#874]
**Environment**:
*(Hint: "Report Extension Issue on Github" command will fill these out for you.)*
VSCode on remote Ubuntu 22.04.3 LTS aarch64

**Version information**

Cloud Code Extension version:v2.2.1

VSCode version:1.85.1

OS: Ubuntu 22.04.3 LTS 5.15.0-1049-oracle #55-Ubuntu SMP Mon Nov 20 19:53:49 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

Cloud SDK: Google Cloud SDK 458.0.1

Skaffold: 

Kubectl:

**Description**: Duet AI keeps crashing

/home/ubuntu/.cache/cloud-code/language-server-binaries/ai-companion/linux_amd64/language_server: 1: Syntax error: word unexpected (expecting ")")
 
Further errors:
 
[Error - 6:23:57 PM] Client Duet AI: connection to server is erroring. Shutting down server.
[Error - 6:23:57 PM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: starting
at A.shutdown (/home/ubuntu/.vscode-server/extensions/googlecloudtools.cloudcode-2.2.1/dist/extension.js:8:12803431)
at A.stop (/home/ubuntu/.vscode-server/extensions/googlecloudtools.cloudcode-2.2.1/dist/extension.js:8:12803012)
at A.stop (/home/ubuntu/.vscode-server/extensions/googlecloudtools.cloudcode-2.2.1/dist/extension.js:8:12965292)
at A.handleConnectionError (/home/ubuntu/.vscode-server/extensions/googlecloudtools.cloudcode-2.2.1/dist/extension.js:8:12809519)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Error - 6:23:57 PM] Server initialization failed.

**Repro step**:
Install Cloud Code extension in VSCode and configure DuetAI

**Comment by itsavvy-ankur** [comment]
hello - I see a similar issue when testing with devcontainers running on Mac M1 
```
This program can only be run on AMD64 processors with v2 microarchitecture support.
[Error - 10:25:26 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 10:25:26 AM] Connection to server got closed. Server will restart.
true
[Error - 10:25:26 AM] Duet AI client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
This program can only be run on AMD64 processors with v2 microarchitecture support.
[Error - 10:25:26 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 10:25:26 AM] Connection to server got closed. Server will restart.
true
[Error - 10:25:26 AM] Duet AI client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:25:26 AM] Client Duet AI: connection to server is erroring. Shutting down server.
[Error - 10:25:26 AM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: startFailed
	at A.shutdown (/home/vscode/.vscode-server/extensions/googlecloudtools.cloudcode-2.2.1/dist/extension.js:8:12803431)
	at A.stop (/home/vscode/.vscode-server/extensions/googlecloudtools.cloudcode-2.2.1/dist/extension.js:8:12803012)
	at A.stop (/home/vscode/.vscode-server/extensions/googlecloudtools.cloudcode-2.2.1/dist/extension.js:8:12965292)
	at A.handleConnectionError (/home/vscode/.vscode-server/extensions/googlecloudtools.cloudcode-2.2.1/dist/extension.js:8:12809519)
	at processTicksAndRejections (node:internal/process/task_queues:95:5)
	at runNextTicks (node:internal/process/task_queues:64:3)
	at process.processImmediate (node:internal/timers:447:9)
[Error - 10:25:26 AM] Server initialization failed.
  Message: write EPIPE
  Code: -32099 
[Error - 10:25:26 AM] Duet AI client: couldn't create connection to server.
  Message: write EPIPE
  Code: -32099 
[Error - 10:25:26 AM] Restarting server failed
  Message: write EPIPE
  Code: -32099 
[Error - 10:25:26 AM] Restarting server failed
  Message: write EPIPE
  Code: -32099 
[Info  - 10:25:26 AM] Connection to server got closed. Server will restart.
true
This program can only be run on AMD64 processors with v2 microarchitecture support.
This program can only be run on AMD64 processors with v2 microarchitecture support.
[Error - 10:25:26 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 10:25:26 AM] Connection to server got closed. Server will restart.
true
[Error - 10:25:26 AM] Duet AI client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:25:26 AM] Server initialization failed.
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Error - 10:25:26 AM] Duet AI client: couldn't create connection to server.
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Error - 10:25:26 AM] Restarting server failed
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Error - 10:25:26 AM] Restarting server failed
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Error - 10:25:26 AM] The Duet AI server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
This program can only be run on AMD64 processors with v2 microarchitecture support.
```

**Comment by glouischandra** [comment]
Hello, can you check the latest release of Cloud Code + Duet AI: v2.3.0 and see if the LS initialization persist?

**Comment by kalona** [comment]
Hi,
still the same issue :(

**Comment by kschaab** [comment]
We have included Linux ARM binaries, you should no longer get this issue.
