### ISSUE TITLE
Error initializing on Linux

### ISSUE THREAD

**Issue by Ortega-Dan** [GoogleCloudPlatform/cloud-code-vscode#879]
Not able to access Minikube:

![image](https://github.com/GoogleCloudPlatform/cloud-code-vscode/assets/24926168/2d1c6547-6d24-4ff4-89b5-4dc1d3b87238)

Latest Cloud-code version: 2.3.0
![image](https://github.com/GoogleCloudPlatform/cloud-code-vscode/assets/24926168/3426d17a-a941-4271-bd64-f588e69882ce)

Verbose logs:
but looks like the specific failure in this log is: 
`[Error]: nodes is forbidden: User "system:anonymous" cannot list resource "nodes" in API group "" at the cluster scope`

```
[2/1/2024, 1:21:57 PM] Running 'kubectl version --client --output json --request-timeout 5s' (unmanaged)
[2/1/2024, 1:21:57 PM] {
  "clientVersion": {
    "major": "1",
    "minor": "28",
    "gitVersion": "v1.28.5",
    "gitCommit": "506050d61cf291218dfbd41ac93913945c9aa0da",
    "gitTreeState": "clean",
    "buildDate": "2023-12-21T02:16:47Z",
    "goVersion": "go1.20.12",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "kustomizeVersion": "v5.0.4-0.20230601165947-6ce0bf390ce3"
}

[2/1/2024, 1:21:57 PM] 'kubectl version --client --output json --request-timeout 5s' exited with code 0 took 74ms (unmanaged)
[2/1/2024, 1:21:57 PM] Running 'skaffold version' (unmanaged)
[2/1/2024, 1:21:57 PM] v2.6.0

[2/1/2024, 1:21:57 PM] 'skaffold version' exited with code 0 took 41ms (unmanaged)
[2/1/2024, 1:21:57 PM] Running 'skaffold version' (unmanaged)
[2/1/2024, 1:21:57 PM] v2.6.0

[2/1/2024, 1:21:57 PM] 'skaffold version' exited with code 0 took 51ms (unmanaged)
[2/1/2024, 1:21:57 PM] Running 'skaffold inspect modules list --filename /home/danortega/Documents/codeprojects/DSG/dsgov-work-manager/skaffold.yaml --format json' (unmanaged)
[2/1/2024, 1:21:57 PM] {"modules":[{"name":"work-manager","path":"/home/danortega/Documents/codeprojects/DSG/dsgov-work-manager/skaffold.yaml","isRoot":true}]}

[2/1/2024, 1:21:57 PM] 'skaffold inspect modules list --filename /home/danortega/Documents/codeprojects/DSG/dsgov-work-manager/skaffold.yaml --format json' exited with code 0 took 47ms (unmanaged)
[2/1/2024, 1:21:57 PM] [warn]Checking if the current context is a local cluster failed with error 'Error: Encountered an error while determining if this is a local cluster. Error: Error: Encountered an error while determining cluster type. Error: h [Error]: nodes is forbidden: User "system:anonymous" cannot list resource "nodes" in API group "" at the cluster scope
    at t.K8sApiErrorHandler.<anonymous> (/home/danortega/.vscode/extensions/googlecloudtools.cloudcode-2.3.0/dist/extension.js:14:10046588)
    at Generator.next (<anonymous>)
    at /home/danortega/.vscode/extensions/googlecloudtools.cloudcode-2.3.0/dist/extension.js:14:10045209
    at new Promise (<anonymous>)
    at a (/home/danortega/.vscode/extensions/googlecloudtools.cloudcode-2.3.0/dist/extension.js:14:10044954)
    at t.K8sApiErrorHandler.handleHttpRequestFailed (/home/danortega/.vscode/extensions/googlecloudtools.cloudcode-2.3.0/dist/extension.js:14:10046290)
    at t.K8sApiErrorHandler.<anonymous> (/home/danortega/.vscode/extensions/googlecloudtools.cloudcode-2.3.0/dist/extension.js:14:10045688)
    at Generator.next (<anonymous>)
    at /home/danortega/.vscode/extensions/googlecloudtools.cloudcode-2.3.0/dist/extension.js:14:10045209
    at new Promise (<anonymous>)
    at a (/home/danortega/.vscode/extensions/googlecloudtools.cloudcode-2.3.0/dist/extension.js:14:10044954)
    at s.ErrorWithActions.name (/home/danortega/.vscode/extensions/googlecloudtools.cloudcode-2.3.0/dist/extension.js:14:10045642)
    at Function.runHandlerFromError (/home/danortega/.vscode/extensions/googlecloudtools.cloudcode-2.3.0/dist/extension.js:14:10555382)
    at t.K8sApiErrorHandler.overrideError (/home/danortega/.vscode/extensions/googlecloudtools.cloudcode-2.3.0/dist/extension.js:14:10046197)
    at t.K8sApiErrorHandler.<anonymous> (/home/danortega/.vscode/extensions/googlecloudtools.cloudcode-2.3.0/dist/extension.js:14:10049042)
    at Generator.throw (<anonymous>)
    at s (/home/danortega/.vscode/extensions/googlecloudtools.cloudcode-2.3.0/dist/extension.js:14:10045062)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  actions: [Array],
  errorType: undefined
}
    at Function.<anonymous> (/home/danortega/.vscode/extensions/googlecloudtools.cloudcode-2.3.0/dist/extension.js:14:10563575)
    at Generator.throw (<anonymous>)
    at s (/home/danortega/.vscode/extensions/googlecloudtools.cloudcode-2.3.0/dist/extension.js:14:10561446)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)'
```

This was not happening some versions ago, and other extensions connecting to Minikube (like the Kubernetes extension) have no issues.

**Comment by neutvd** [comment]
Hi @Ortega-Dan,
did you ever manage to resolve this? I'm running into the exact same issue.

**Comment by ttosta-google** [comment]
Hello @neutvd,

Please submit an issue using the Submit Feedback button. This will give us logs to better debug this issue.

Thanks!

**Comment by neutvd** [comment]
Hi @ttosta-google,

I just sent the feedback form. I am using the latest 2.16.7 version btw.

**Comment by glouischandra** [comment]
Hello @neutvd we're having a problem trying to repro the issue currently, is there by any chance you can send us the minikube log file, should be located in " ~/.minikube/logs/lastStart.txt"

Also is there any chance you're using L7 loadbalancing in your setup: https://github.com/kelseyhightower/kubernetes-the-hard-way/issues/438, if so this issue might be related.

**Comment by neutvd** [comment]
Hi @glouischandra sorry it took me so long to respond. I have attached the lastStart.txt file from minikube.

[lastStart.txt](https://github.com/user-attachments/files/17339047/lastStart.txt)

I do have some clusters running on AWS EKS that use L7 load balancing, but these are not configured in the default ~/.kube/config file. I have to set a `KUBECONFIG` environment variable specifically to have `kubectl` and such pointing to it. Only minikube is configured in the default config file and it's what VSCode should be using when I run into this.

**Comment by finsterdexter** [comment]
I'm currently hitting this as well. Newly created minikube cluster, just installed cloudcode extension. I'm using minikube outside of cloud code dependencies, fwiw.

**Comment by kschaab** [comment]
Are you failing to connect to the minikube cluster on Linux with the same error?  The reason I ask is there was another issue that was introduced with the latest golang implementation and is addressed by a newer version of skaffold.  Can you provide the lastStart for your minikube cluster?

**Comment by neutvd** [comment]
In my case everything is on Linux as that is what my development machine runs. However, I think you are responding to @finsterdexter ? I can send you my lastStart, but since upgrade to lastest skaffold and cloud code, I run into a different issue it seems.
```
2025-04-01 16:02:19.780 [error] command 'cloudcode.runK8sAppExplorerTitle' not found: Error: command 'cloudcode.runK8sAppExplorerTitle' not found
```

**Comment by finsterdexter** [comment]
> Are you failing to connect to the minikube cluster on Linux with the same error? The reason I ask is there was another issue that was introduced with the latest golang implementation and is addressed by a newer version of skaffold. Can you provide the lastStart for your minikube cluster?

Yeah, same error trying to do anything at all with cloud code extension, along the lines of: nodes is forbidden: User "system:anonymous" cannot list resource "nodes" in API group "" at the cluster scope.

When trying to debug a pod, I get pods is forbidden, etc. just depends on which resource the extension is trying to access. The kubernetes extension doesn't seem to have any issues getting info or interacting with the minikube cluster, so I don't know.

As far as laststart log, it leaks some proprietary info like private container repo info and some details about our platform I don't want to share. Is there anything I can look for specifically in those logs?

Not sure about Skaffold, I don't really do anything with Skaffold. The only thing I use cloud code extension for is attaching to vsdbg inside dotnet pods in minikube. I don't use GCP for anything.

**Comment by SkowRon96** [comment]
Is there any solution to this problem? Whether I try to connect to a custom kubernetes cluster or a newly set up minikube I get the same error.

**Comment by neutvd** [comment]
I finally resorted to ask ChatGPT a few days ago, and surprisingly it gave me an answer that I have not been able to find anywhere using normal web searches. The problem seems to be in the way minikube sets the authentication/authorization certificates:

```yaml
users:
- name: minikube
  user:
    client-certificate: /home/username/.minikube/profiles/minikube/client.crt
    client-key: /home/username/.minikube/profiles/minikube/client.key

```
From what I remember ChatGPT telling me is dat the Google Cloud Code plugin is not capable of fetching the certificates, unless the certificates are included directly in the ${KUBE_CONFIG} file. Minikube stores them in a file and then adds the path to the config file and Google Cloud Code plugin for VSCode cannot parse it. Someone with more knowledge about the internals might be able to confirm. It's AI after all, so caveat emptor.

**Comment by SkowRon96** [comment]
In my case, the authorization data is not in the form of file paths but in the form of client-certificate-data and client-key-data keys. However, the same problem still occurs. Is there any working solution?
