### ISSUE TITLE
getting issue while installing gccloud

### ISSUE THREAD

**Issue by pramod-shenkar** [GoogleCloudPlatform/cloud-code-vscode#898]
getting error while installing gcloud with cloudcode extenion

COMMMAND =>
curl https://sdk.cloud.google.com | bash
OUTPUT => 
.
.
.
google-cloud-sdk/platform/ext-runtime/ruby/lib/gae_ext_runtime/__init__.py
google-cloud-sdk/platform/ext-runtime/ruby/lib/gae_ext_runtime/comm.py
google-cloud-sdk/platform/ext-runtime/ruby/runtime.yaml
google-cloud-sdk/platform/ext-runtime/ruby/templates/Dockerfile.template
google-cloud-sdk/platform/ext-runtime/ruby/templates/dockerignore.template
google-cloud-sdk/platform/ext-runtime/ruby/test/runtime_test.py
google-cloud-sdk/rpm/mapping/command_mapping.yaml
google-cloud-sdk/rpm/mapping/component_mapping.yaml

/home/gopher.pramod/google-cloud-sdk/install.sh
Welcome to the Google Cloud CLI!

To help improve the quality of this product, we collect anonymized usage data
and anonymized stacktraces when crashes are encountered; additional information
is available at <https://cloud.google.com/sdk/usage-statistics>. This data is
handled in accordance with our privacy policy
<https://cloud.google.com/terms/cloud-privacy-notice>. You may choose to opt in this
collection now (by choosing 'Y' at the below prompt), or at any time in the
future by running the following command:

    gcloud config set disable_usage_reporting false

Do you want to help improve the Google Cloud CLI (y/N)?  y

This will install all the core command line tools necessary for working with
the Google Cloud Platform.

Beginning update. This process may take several minutes.
Traceback (most recent call last):
  File "/home/gopher.pramod/google-cloud-sdk/lib/third_party/urllib3/connectionpool.py", line 717, in urlopen
    httplib_response = self._make_request(
  File "/home/gopher.pramod/google-cloud-sdk/lib/third_party/urllib3/connectionpool.py", line 406, in _make_request
    self._validate_conn(conn)
  File "/home/gopher.pramod/google-cloud-sdk/lib/third_party/urllib3/connectionpool.py", line 1057, in _validate_conn
    conn.connect()
  File "/home/gopher.pramod/google-cloud-sdk/lib/third_party/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/home/gopher.pramod/google-cloud-sdk/lib/third_party/urllib3/util/ssl_.py", line 454, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/home/gopher.pramod/google-cloud-sdk/lib/third_party/urllib3/util/ssl_.py", line 498, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1069, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1338, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gopher.pramod/google-cloud-sdk/lib/third_party/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/gopher.pramod/google-cloud-sdk/lib/third_party/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/home/gopher.pramod/google-cloud-sdk/lib/third_party/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='dl.google.com', port=443): Max retries exceeded with url: /dl/cloudsdk/channels/rapid/components-2.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gopher.pramod/google-cloud-sdk/bin/bootstrapping/install.py", line 372, in <module>
    main()
  File "/home/gopher.pramod/google-cloud-sdk/bin/bootstrapping/install.py", line 345, in main
    Install(
  File "/home/gopher.pramod/google-cloud-sdk/bin/bootstrapping/install.py", line 205, in Install
    InstallOrUpdateComponents(to_install, compile_python, update=update)
  File "/home/gopher.pramod/google-cloud-sdk/bin/bootstrapping/install.py", line 256, in InstallOrUpdateComponents
    _CLI.Execute(
  File "/home/gopher.pramod/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 1024, in Execute
    self._HandleAllErrors(exc, command_path_string, specified_arg_names)
  File "/home/gopher.pramod/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 1061, in _HandleAllErrors
    exceptions.HandleError(exc, command_path_string, self.__known_error_handler)
  File "/home/gopher.pramod/google-cloud-sdk/lib/googlecloudsdk/calliope/exceptions.py", line 557, in HandleError
    core_exceptions.reraise(exc)
  File "/home/gopher.pramod/google-cloud-sdk/lib/googlecloudsdk/core/exceptions.py", line 149, in reraise
    six.reraise(type(exc_value), exc_value, tb)
  File "/home/gopher.pramod/google-cloud-sdk/lib/third_party/six/__init__.py", line 719, in reraise
    raise value
  File "/home/gopher.pramod/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 998, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/home/gopher.pramod/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 815, in Run
    resources = command_instance.Run(args)
  File "/home/gopher.pramod/google-cloud-sdk/lib/surface/components/update.py", line 125, in Run
    update_manager.Update(
  File "/home/gopher.pramod/google-cloud-sdk/lib/googlecloudsdk/core/updater/update_manager.py", line 1016, in Update
    install_state, diff = self._GetStateAndDiff(
  File "/home/gopher.pramod/google-cloud-sdk/lib/googlecloudsdk/core/updater/update_manager.py", line 719, in _GetStateAndDiff
    latest_snapshot = self._GetLatestSnapshot(version=version,
  File "/home/gopher.pramod/google-cloud-sdk/lib/googlecloudsdk/core/updater/update_manager.py", line 702, in _GetLatestSnapshot
    return snapshots.ComponentSnapshot.FromURLs(
  File "/home/gopher.pramod/google-cloud-sdk/lib/googlecloudsdk/core/updater/snapshots.py", line 175, in FromURLs
    data = [
  File "/home/gopher.pramod/google-cloud-sdk/lib/googlecloudsdk/core/updater/snapshots.py", line 176, in <listcomp>
    (ComponentSnapshot._DictFromURL(
  File "/home/gopher.pramod/google-cloud-sdk/lib/googlecloudsdk/core/updater/snapshots.py", line 200, in _DictFromURL
    response = installers.MakeRequest(url, command_path)
  File "/home/gopher.pramod/google-cloud-sdk/lib/googlecloudsdk/core/updater/installers.py", line 115, in MakeRequest
    return _RawRequest(url, headers=headers, timeout=timeout)
  File "/home/gopher.pramod/google-cloud-sdk/lib/googlecloudsdk/core/updater/installers.py", line 163, in _RawRequest
    return retryer.RetryOnException(
  File "/home/gopher.pramod/google-cloud-sdk/lib/googlecloudsdk/core/util/retry.py", line 201, in RetryOnException
    exceptions.reraise(exc_info[1], tb=exc_info[2])
  File "/home/gopher.pramod/google-cloud-sdk/lib/googlecloudsdk/core/exceptions.py", line 149, in reraise
    six.reraise(type(exc_value), exc_value, tb)
  File "/home/gopher.pramod/google-cloud-sdk/lib/third_party/six/__init__.py", line 719, in reraise
    raise value
  File "/home/gopher.pramod/google-cloud-sdk/lib/googlecloudsdk/core/util/retry.py", line 182, in TryFunc
    return func(*args, **kwargs), None
  File "/home/gopher.pramod/google-cloud-sdk/lib/googlecloudsdk/core/updater/installers.py", line 196, in _ExecuteRequestAndRaiseExceptions
    response = requests_session.get(
  File "/home/gopher.pramod/google-cloud-sdk/lib/third_party/requests/sessions.py", line 557, in get
    return self.request('GET', url, **kwargs)
  File "/home/gopher.pramod/google-cloud-sdk/lib/googlecloudsdk/core/transport.py", line 269, in WrappedRequest
    response = orig_request(*modified_args, **modified_kwargs)
  File "/home/gopher.pramod/google-cloud-sdk/lib/googlecloudsdk/core/requests.py", line 246, in WrappedRequest
    return orig_request_method(*args, **kwargs)
  File "/home/gopher.pramod/google-cloud-sdk/lib/third_party/requests/sessions.py", line 544, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/gopher.pramod/google-cloud-sdk/lib/third_party/requests/sessions.py", line 657, in send
    r = adapter.send(request, **kwargs)
  File "/home/gopher.pramod/google-cloud-sdk/lib/third_party/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='dl.google.com', port=443): Max retries exceeded with url: /dl/cloudsdk/channels/rapid/components-2.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1131)')))

---------------------------------------------------------------------------------------

Also got following output for command:

COMMMAND =>
gcloud components install alpha beta skaffold minikube kubectl gke-gcloud-auth-plugin

OUTPUT => 
ERROR: gcloud crashed (SSLError): HTTPSConnectionPool(host='dl.google.com', port=443): Max retries exceeded with url: /dl/cloudsdk/channels/rapid/components-v474.0.0.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1131)')))

gcloud's default CA certificates failed to verify your connection, which can happen if you are behind a proxy or firewall.
To use a custom CA certificates file, please run the following command:
  gcloud config set core/custom_ca_certs_file /path/to/ca_certs

If you would like to report this issue, please run the following command:
  gcloud feedback

To check gcloud for common problems, please run the following command:

**Comment by sripasg** [comment]
That seems like a bug. What is the version of the extension you are trying to install ?

**Comment by glouischandra** [comment]
Also is the machine behind proxy/firewall, especially enterprise proxy?

**Comment by davidponder** [comment]
Hello!

We'll close this item due to lack of activity. Please feel free to re-open with answers to the above questions if this is still an issue; thanks!
