### ISSUE TITLE
Extenstion not starting

### ISSUE THREAD

**Issue by unique-serghei** [GoogleCloudPlatform/cloud-code-vscode#949]
Type: <b>Bug</b>

Extension fails to start

Extension version: 2.19.0
VS Code version: Code - Insiders 1.95.0-insider (defe52dc43e6f5d861f55600ff01f7553fac7eaf, 2024-10-22T05:04:01.628Z)
OS version: Windows_NT x64 10.0.26100
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i9-13905H (20 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.73GB (38.99GB free)|
|Process Argv|--crash-reporter-id 9f10a803-8e45-4194-9a1c-4238c55bbeea|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
vsaa593cf:30376535
py29gd2263:31024238
vscaat:30438846
c4g48928:30535728
962ge761:30841072
pythongtdpath:30726887
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
cppperfnew:30980852
pythonait:30973460
bdiig495:31013172
dvdeprecation:31040973
dwnewjupyter:31046869
nb_pri_only:31057983
nativerepl1:31134653
refactort:31084545
pythonrstrctxt:31093868
wkspc-onlycs-t:31132770
nativeloc1:31118317
wkspc-ranged-t:31151552
cf971741:31144450
e80f6927:31120813
autoexpandse:31146404
i21gd607:31141543
iacca1:31150324
notype1:31143044
f8igb616:31140137
dwcopilot:31158714
g7688163:31155431

```

</details>

**Comment by unique-serghei** [comment]
Command cloudcode.signin already registered by Gemini Code Assist + Google Cloud Code (googlecloudtools.cloudcode)

**Comment by ruffp** [comment]
Same issue for me since around one week: the chat is not starting (progress bar sliding) and a clock in the chat icon.

Version: 1.94.2 (user setup)
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
Date: 2024-10-09T16:08:44.566Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045

I tried to uninstall and disabled the Google extension but the plugin does not start anymore. 
It still works in Intellij IDEA. 

I found this error in the `exthost.log` file of vscode: 

> 2024-10-28 08:23:05.321 [error] SyntaxError: Unexpected token ' ', "          "... is not valid JSON
>     at JSON.parse (<anonymous>)
>     at t.FsOauthDataStore.<anonymous> (c:\Users\myuser\.vscode\extensions\googlecloudtools.cloudcode-2.19.0\dist\extension.js:14:9409488)
>     at Generator.next (<anonymous>)
>     at i (c:\Users\myuser\.vscode\extensions\googlecloudtools.cloudcode-2.19.0\dist\extension.js:14:9405167)

I am not sure if you have the same issue.

(log is in C:\Users\<myuser>\AppData\Roaming\Code\logs\<timestamp>\window1\exthost)

**Comment by maxrandolph** [comment]
Hi @unique-serghei  and @ruffp. Would it be possible for you to reproduce this issue and to share the logs with us? It is possible to send logs through the feedback section of the extension.

<img width="677" alt="image" src="https://github.com/user-attachments/assets/7af8cb81-271e-4fe5-a6a5-e21f02a794be">

Thanks.
