### ISSUE TITLE
Extension will not start

### ISSUE THREAD

**Issue by MonkeyNinja** [GoogleCloudPlatform/cloud-code-vscode#959]
Type: <b>Bug</b>

Extension will not start 

This is in the  Extension Host output log nb the NULLs appear as white on red highlighted NULL chars and wont paste here I had to recreate

2024-11-07 16:56:18.303 [error] Activating extension googlecloudtools.cloudcode failed due to an error:
2024-11-07 16:56:18.303 [error] SyntaxError: Unexpected token 'NULL', "NULLx10" ...is not valid JSON
    at JSON.parse (<anonymous>)
    at t.FsOauthDataStore.<anonymous> (c:\Users\adrian.martin\.vscode\extensions\googlecloudtools.cloudcode-2.20.0\dist\extension.js:14:9418854)
    at Generator.next (<anonymous>)
    at i (c:\Users\adrian.martin\.vscode\extensions\googlecloudtools.cloudcode-2.20.0\dist\extension.js:14:9414533)

Extension version: 2.20.0
VS Code version: Code 1.95.1 (65edc4939843c90c34d61f4ce11704f09d3e5cb6, 2024-10-31T05:14:54.222Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1255U (12 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.69GB (5.81GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/adrian.martin/Documents/Projects/cosmosdb-queries --crash-reporter-id 366ffa0d-363b-42ed-aa79-bdce4078f79d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
nativeloc1:31134641
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
g7688163:31175162

```

</details>

**Comment by tim-lebedkov** [comment]
creating the  ~/.cache/cloud-code directory fixed this for me.

**Comment by rroethof** [comment]
I actually had to delete the cache dir.
